export type CommunicationsAudience = "schools" | "parents" | "teachers" | "executives";

export type CommunicationsTemplate = {
  id: string;
  name: string;
  audience: CommunicationsAudience;
  category: string;
  subject: string;
  body: string;
  mergeFields: string[];
};

const schoolContact = "If you need help, reply to this message or contact {{center.name}} at {{center.phone}} or {{center.email}}.";

export const communicationsKitTemplates: CommunicationsTemplate[] = [
  { id: "kit-parent-welcome", name: "Parent portal welcome and login", audience: "parents", category: "onboarding", subject: "Welcome to the {{center.name}} parent portal", body: "Hi {{guardian.firstName}},\n\nYour family now has access to The BEE Suite parent portal for daily reports, photos, messages, documents, attendance, and billing. Sign in with {{guardian.email}}. If this is your first login, use the setup instructions provided by your school and change your password from Profile Settings.\n\nStart here: https://thebeesuite.io/parents\n\nFor pickup, custody, health, or same-day schedule changes, always contact the school directly.\n\n" + schoolContact, mergeFields: ["guardian.firstName", "guardian.email", "center.name", "center.phone", "center.email"] },
  { id: "kit-enrollment-start", name: "Enrollment approved and start-day steps", audience: "parents", category: "enrollment", subject: "{{child.firstNames}} is ready to start at {{center.name}}", body: "Hi {{guardian.firstName}},\n\nEnrollment for {{child.names}} is approved. Before the first day, please review the parent portal, confirm all guardians and emergency contacts, upload any requested health or permission documents, review the tuition schedule, and verify the classroom schedule.\n\nOn the first day, bring any school-requested supplies and allow extra time for authorized pickup setup.\n\n" + schoolContact, mergeFields: ["guardian.firstName", "child.firstNames", "child.names", "center.name", "center.phone", "center.email"] },
  { id: "kit-document-action", name: "Required document action", audience: "parents", category: "documents", subject: "Action needed: update a record for {{child.names}}", body: "Hi {{guardian.firstName}},\n\nA required record for {{child.names}} needs attention. Open the parent portal, review the Documents area, and upload the requested item. The school must verify the document before the record is marked complete.\n\nDo not email medical, custody, banking, or other sensitive files unless the school gives you an approved secure method.\n\n" + schoolContact, mergeFields: ["guardian.firstName", "child.names", "center.name", "center.phone", "center.email"] },
  { id: "kit-billing-autopay", name: "Billing, invoices, and autopay guide", audience: "parents", category: "billing", subject: "How billing and payments work at {{center.name}}", body: "Hi {{guardian.firstName}},\n\nYour parent portal shows invoices, payments, credits, and the current family balance. Open Billing to review charges before paying. If autopay is offered, confirm the amount, payment method, timing, and any displayed processing disclosure before authorizing it. ACH payments may take several business days to settle.\n\nFor tuition policy, discounts, subsidies, refunds, or payment arrangements, contact the school office. Never send card or bank credentials by email.\n\n" + schoolContact, mergeFields: ["guardian.firstName", "center.name", "center.phone", "center.email"] },
  { id: "kit-attendance", name: "Attendance and kiosk procedure", audience: "parents", category: "attendance", subject: "Check-in, checkout, and absence procedure for {{child.names}}", body: "Hi {{guardian.firstName}},\n\nUse the school kiosk or approved staff process every day for check-in and checkout. Only authorized guardians may complete pickup. Report absences and schedule changes through the parent portal or directly to the school as instructed.\n\nFor a same-day pickup change, custody concern, illness, or emergency, call the school directly—do not rely on an unread portal message.\n\n" + schoolContact, mergeFields: ["guardian.firstName", "child.names", "center.name", "center.phone", "center.email"] },
  { id: "kit-daily-reports", name: "Daily reports and photos guide", audience: "parents", category: "classroom", subject: "Daily reports and classroom moments for {{child.names}}", body: "Hi {{guardian.firstName}},\n\nTeachers use The BEE Suite to share approved daily care entries, notes, activities, and photos. Open Daily Reports and Photos in the parent portal to review updates. Some entries may appear after teacher or director review.\n\nUse Messages for routine questions. Contact the school immediately for urgent health, safety, custody, or pickup concerns.\n\n" + schoolContact, mergeFields: ["guardian.firstName", "child.names", "center.name", "center.phone", "center.email"] },
  { id: "kit-incident", name: "Incident report review procedure", audience: "parents", category: "incidents", subject: "Incident report available for review", body: "Hi {{guardian.firstName}},\n\nAn incident record is available for your review. The report documents observed facts and the actions taken by staff. Please review it in the parent portal and follow the school’s acknowledgment instructions. A director completes the administrative review.\n\nThis message is not a substitute for an urgent phone call. Contact the school directly with immediate medical or safety questions.\n\n" + schoolContact, mergeFields: ["guardian.firstName", "center.name", "center.phone", "center.email"] },
  { id: "kit-director-launch", name: "Director dashboard launch checklist", audience: "schools", category: "school_setup", subject: "Your {{center.name}} BEE Suite launch checklist", body: "Hello {{sender.name}},\n\nComplete School Setup before inviting families: verify the school profile and hours; classrooms, capacity, and ratios; staff roles and schedules; family and child records; tuition and billing rules; documents and permissions; notification settings; calendar closures; and the FTE workflow.\n\nThen run the director, teacher, parent, kiosk, enrollment, billing, document, and reporting smoke tests. Keep sensitive actions role-gated and human-reviewed.\n\nGuide: https://thebeesuite.io/resources", mergeFields: ["sender.name", "center.name"] },
  { id: "kit-teacher-invite", name: "Teacher invitation and daily workflow", audience: "teachers", category: "staff", subject: "Your {{center.name}} teacher dashboard", body: "Hi {{sender.name}},\n\nYour teacher dashboard is ready. Sign in through https://thebeesuite.io/teachers. Start each day by reviewing the assigned classroom and attendance. During the day, record care activities and approved media. Before checkout, complete each child’s daily report and escalate incidents, medication, custody, or safety concerns to a director.\n\nNever share login credentials or use another staff member’s account.", mergeFields: ["sender.name", "center.name"] },
  { id: "kit-fte-weekly", name: "Weekly FTE review and submission", audience: "schools", category: "fte_reports", subject: "Weekly FTE review is ready for {{center.name}}", body: "Hello {{sender.name}},\n\nBefore submitting this week’s FTE report, reconcile active enrollment, full-time and part-time schedules, age-group totals, attendance exceptions, licensed capacity, occupancy, billing totals, accounts receivable, new starts, and withdrawals. Resolve any variance shown on the form.\n\nSubmit only after director review. Approved reports require the executive correction workflow.\n\nOpen FTE Reports: https://thebeesuite.io/fte-reports", mergeFields: ["sender.name", "center.name"] },
  { id: "kit-school-billing", name: "School billing close procedure", audience: "schools", category: "billing", subject: "Billing close checklist for {{center.name}}", body: "Hello {{sender.name}},\n\nFor the weekly billing close: review draft and open invoices; confirm tuition and fee line items; reconcile successful, pending, failed, refunded, and agency payments; review credits and family balances; document approved adjustments; and follow up on modest outstanding balances using the school’s policy.\n\nDo not mark an invoice paid until the payment is confirmed. Keep subsidy and parent-responsibility balances clearly separated.", mergeFields: ["sender.name", "center.name"] },
  { id: "kit-executive-review", name: "Executive multi-location review", audience: "executives", category: "reporting", subject: "Kid City USA weekly operating review", body: "Hello {{sender.name}},\n\nReview the multi-location dashboard for enrollment and occupancy, FTE submission status, attendance exceptions, staffing and ratios, billing collections and AR, compliance tasks, incidents awaiting review, document expirations, and open CRM follow-up.\n\nUse executive correction and approval workflows for audited changes. Export reports only when needed and handle child, family, staff, and billing data according to role and retention requirements.", mergeFields: ["sender.name"] },
];

export const processFaqs = [
  { audience: "Parents", question: "How do I access the parent portal for the first time?", answer: "Open the Parent login page, use the guardian email your school has on file, and follow the first-login or password-reset instructions. After signing in, verify your profile and change your password from Profile Settings." },
  { audience: "Parents", question: "What should I do if my child or family information is wrong?", answer: "Send a routine correction through the parent portal or contact the school office. For an error affecting same-day pickup, custody, medication, allergy, or emergency contacts, call the school immediately." },
  { audience: "Parents", question: "How do check-in and checkout work?", answer: "Use the school’s kiosk or staff-assisted process every day. Only authorized people may complete pickup. Never share a kiosk PIN, and call the school for same-day pickup changes." },
  { audience: "Parents", question: "Where can I report an absence or schedule change?", answer: "Use the parent portal when your school accepts online absence notices. For same-day or urgent changes, call the school directly and follow its attendance policy." },
  { audience: "Parents", question: "When will daily reports and photos appear?", answer: "Teachers publish approved care entries, notes, and media during or after the school day. Some content may wait for teacher or director review. Contact the classroom for missing routine updates." },
  { audience: "Parents", question: "How do I upload enrollment, medical, or permission documents?", answer: "Open Documents in the parent portal, choose the requested record, and use the secure upload flow. The school reviews uploads before marking them complete. Do not send sensitive files through ordinary email." },
  { audience: "Parents", question: "How do invoices, balances, and autopay work?", answer: "Billing shows invoices, payments, credits, and the current family balance. Review the amount and payment method before authorizing payment. ACH may remain pending for several business days. Tuition policy questions belong with the school office." },
  { audience: "Parents", question: "What if a payment fails or my balance looks wrong?", answer: "Do not submit repeated payments while one is pending. Review the payment status, then contact the school with the invoice number and date. Never email card numbers or bank credentials." },
  { audience: "Parents", question: "How are incident reports handled?", answer: "Staff record observed facts and actions taken, a director completes administrative review, and the family receives the approved report and acknowledgment steps. Urgent health and safety communication still happens directly." },
  { audience: "Schools", question: "What must a director complete before launch?", answer: "Verify the school profile, classrooms, ratios, staff, families, tuition rules, documents, communications, calendar, compliance, and FTE workflow; then test director, teacher, parent, kiosk, billing, enrollment, documents, and reporting." },
  { audience: "Schools", question: "What is the daily director operating loop?", answer: "Review dashboard alerts, attendance and ratios, new leads and tasks, family messages, incidents, documents, billing exceptions, staff coverage, and end-of-day report completion. Assign an owner and due time to every exception." },
  { audience: "Schools", question: "How should teachers use the classroom dashboard?", answer: "Confirm the classroom assignment, mark attendance through the approved check-in process, record daily care and activities, share only approved media, finish reports before checkout, and escalate sensitive decisions to a director." },
  { audience: "Schools", question: "What should be reconciled before submitting FTE?", answer: "Match active enrollment, full-time and part-time schedules, age-group totals, attendance exceptions, licensed capacity, occupancy, billing totals, AR, new starts, and withdrawals. Resolve form variances before submission." },
  { audience: "Schools", question: "How should weekly billing close be performed?", answer: "Review invoice statuses and line items, reconcile payments and refunds, verify credits and adjustments, separate subsidy and family responsibility, and follow up according to policy. Never mark unconfirmed funds paid." },
  { audience: "Schools", question: "Who can change approved FTE or sensitive records?", answer: "Use role-based correction and approval workflows. Approved FTE reports require executive correction. Custody, medical, incident, billing, compliance, and deletion decisions remain human-reviewed and auditable." },
  { audience: "Schools", question: "What information should never be sent through ordinary email?", answer: "Do not send full payment credentials, bank logins, medical files, custody files, government identifiers, passwords, or unapproved child media. Use the secure in-app workflow or an approved protected channel." },
  { audience: "Schools", question: "How should a school request technical support?", answer: "Include the user role, school, login email, page, time, steps taken, and a safe screenshot. Remove child, family, billing, medical, and custody details unless support provides a secure upload path." },
  { audience: "Everyone", question: "What requires a phone call instead of a portal message?", answer: "Immediate safety or medical issues, custody concerns, pickup changes, same-day attendance changes, urgent billing or policy decisions, and any record error that affects today’s care should go directly to the school." },
] as const;

const guideByCategory: Record<string, string> = {
  onboarding: "/brand/the-bee-suite/explainers/bee-suite-parent-dashboard-guide-2026-06-25.png",
  enrollment: "/brand/the-bee-suite/explainers/BEE_SUITE_EXPLAINER_02-inquiry-to-enrolled-family_2026-06-08.png",
  billing: "/brand/the-bee-suite/usage/bee-suite-director-operations.png",
  attendance: "/brand/the-bee-suite/usage/bee-suite-lobby-check-in.png",
  classroom: "/brand/the-bee-suite/usage/bee-suite-classroom-daily-updates.png",
  staff: "/brand/the-bee-suite/explainers/kid-city-teacher-profile-setup-roadmap.svg",
  school_setup: "/brand/the-bee-suite/explainers/bee-suite-school-launch-swimlane-2026-07-01.svg",
  fte_reports: "/brand/the-bee-suite/explainers/bee-suite-director-dashboard-guide-2026-06-25.png",
  reporting: "/brand/the-bee-suite/explainers/bee-suite-getting-started-platform-map-2026-07-01.svg",
};

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character);
}

function linkify(value: string) {
  return escapeHtml(value).replace(/https:\/\/[^\s<]+/g, (url) => `<a href="${url}" style="color:#9a6700;font-weight:700">${url}</a>`);
}

export function buildBeeSuiteEmailHtml({ title, body, category = "general", appBaseUrl = "https://thebeesuite.io" }: { title: string; body: string; category?: string; appBaseUrl?: string }) {
  const base = appBaseUrl.replace(/\/+$/, "");
  const guide = guideByCategory[category];
  const paragraphs = body.split(/\n{2,}/).map((paragraph) => `<p style="margin:0 0 18px;line-height:1.65;color:#334155">${linkify(paragraph).replace(/\n/g, "<br>")}</p>`).join("");
  return `<!doctype html><html><body style="margin:0;background:#f4f1e8;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f1e8;padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:680px;background:#ffffff;border-radius:22px;overflow:hidden;border:1px solid #e5dfcf"><tr><td style="background:#080a0d;padding:24px 30px"><img src="${base}/brand/the-bee-suite/logo-primary-horizontal-white.png" width="230" alt="The BEE Suite" style="display:block;max-width:100%;height:auto"></td></tr>${guide ? `<tr><td><img src="${base}${guide}" width="680" alt="BEE Suite process guide" style="display:block;width:100%;height:auto"></td></tr>` : ""}<tr><td style="padding:32px 34px"><div style="color:#a16207;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;margin-bottom:10px">THE BEE SUITE • HUMAN-REVIEWED WORKFLOW</div><h1 style="margin:0 0 22px;color:#111827;font-size:28px;line-height:1.2">${escapeHtml(title)}</h1>${paragraphs}<div style="margin-top:26px;padding:16px 18px;border-radius:14px;background:#fff8dc;color:#713f12;font-size:13px;line-height:1.55"><strong>Safety note:</strong> Contact the school directly for urgent health, safety, custody, pickup, or same-day care decisions.</div></td></tr><tr><td style="padding:22px 34px;background:#111827;color:#cbd5e1;font-size:12px;line-height:1.6">The BEE Suite keeps enrollment, classroom operations, family communication, billing, compliance, and reporting connected. Do not reply with passwords, payment credentials, medical files, or custody documents.</td></tr></table></td></tr></table></body></html>`;
}
