import { createHash } from "node:crypto";

export const INTERNAL_SIGNATURE_PENDING_KEY = "internal_signature_pending";
export const LEGACY_SIGNATURE_PROVIDER_PENDING_KEY = "signature_provider_pending";
export const SIGNATURE_CONSENT_TEXT =
  "I agree that typing my name and submitting this document is my electronic signature for this school record.";

function clean(value: unknown) {
  return typeof value === "string" ? value.trim().replace(/\s+/g, " ") : "";
}

export function isInternalSignatureRequest(record: { storageKey?: string | null }) {
  const storageKey = clean(record.storageKey).toLowerCase();
  return storageKey === INTERNAL_SIGNATURE_PENDING_KEY || storageKey === LEGACY_SIGNATURE_PROVIDER_PENDING_KEY;
}

export function normalizeSignatureName(value: unknown) {
  return clean(value).slice(0, 120);
}

export function validateSignatureCapture(input: {
  required: boolean;
  signerName?: unknown;
  consentAccepted?: boolean;
}) {
  if (!input.required) return { ok: true as const, signerName: normalizeSignatureName(input.signerName) };

  const signerName = normalizeSignatureName(input.signerName);
  if (!signerName) {
    return {
      ok: false as const,
      status: 400,
      error: "Typed signature is required for this document.",
    };
  }
  if (!input.consentAccepted) {
    return {
      ok: false as const,
      status: 400,
      error: "Signature consent must be accepted before submitting.",
    };
  }

  return { ok: true as const, signerName };
}

export function signatureEvidenceHash(parts: Array<string | null | undefined>) {
  const hash = createHash("sha256");
  hash.update(parts.map((part) => part ?? "").join("\n"));
  return hash.digest("hex");
}

export function buildInternalSignatureCertificate(input: {
  documentId: string;
  documentName: string;
  documentType: string;
  familyName: string;
  childName?: string | null;
  signerName: string;
  signerEmail: string;
  signerUserId: string;
  signedAt: Date;
  evidenceHash: string;
}) {
  const lines = [
    "The BEE Suite Internal E-Signature Certificate",
    "",
    `Document ID: ${input.documentId}`,
    `Document: ${input.documentName}`,
    `Type: ${input.documentType}`,
    `Family: ${input.familyName}`,
    input.childName ? `Child: ${input.childName}` : null,
    "",
    `Signer name: ${input.signerName}`,
    `Signer email: ${input.signerEmail}`,
    `Signer user ID: ${input.signerUserId}`,
    `Signed at UTC: ${input.signedAt.toISOString()}`,
    `Consent: ${SIGNATURE_CONSENT_TEXT}`,
    `Evidence hash: ${input.evidenceHash}`,
    "",
    "This certificate was generated by the internal The BEE Suite parent portal signature flow.",
  ].filter((line): line is string => line !== null);

  return Buffer.from(`${lines.join("\n")}\n`, "utf8");
}
