import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

test("director bulk autopay requires an exact reviewed balance snapshot", () => {
  const route = readFileSync("src/app/api/billing/autopay/route.ts", "utf8");
  const actions = readFileSync("src/components/payment-autopay-actions.tsx", "utf8");
  const livePages = readFileSync("src/components/live-ops-pages.tsx", "utf8");
  const page = readFileSync("src/app/[slug]/page.tsx", "utf8");
  const processing = readFileSync("src/lib/autopay-processing.ts", "utf8");
  const familyPayment = readFileSync("src/app/api/billing/family-payment/route.ts", "utf8");
  const terminalPayment = readFileSync("src/app/api/billing/terminal-payment/route.ts", "utf8");
  const paymentClaims = readFileSync("src/lib/stripe-payment-claims.ts", "utf8");
  const workbench = readFileSync("src/components/billing-workbench.tsx", "utf8");
  const paymentRequests = readFileSync("src/app/api/billing/payment-method-requests/route.ts", "utf8");

  assert.match(route, /Review eligible family balances before processing autopay/);
  assert.match(route, /JSON\.stringify\(actual\) !== JSON\.stringify\(expected\)/);
  assert.match(route, /invoiceIds: expected\.map/);
  assert.match(route, /expectedAmountCentsByInvoiceId/);
  assert.doesNotMatch(route, /for \(const item of expected\)/);
  assert.match(actions, /reviewedInvoices/);
  assert.match(actions, /Process all reviewed balances/);
  assert.match(actions, /Process family autopay/);
  assert.match(actions, /Payment configuration is checked automatically/);
  assert.match(livePages, /data\.canProcessAutopay \? <PaymentAutopayActions \/>/);
  assert.match(page, /canProcessAutopay: canManageBilling\(user\)/);
  assert.match(actions, /disabled=\{isPending \|\| !readyToProcess\}/);
  assert.match(processing, /take: limit \+ 1/);
  assert.match(processing, /input\.invoiceIds\?\.length/);
  assert.match(processing, /expectedAmountCents !== creditAllocation\.stripeChargePrincipalCents/);
  assert.match(processing, /cursor: \{ id: input\.cursorInvoiceId \}/);
  assert.match(actions, /Review next batch/);
  assert.match(actions, /summary\?\.dryRun && summary\.wouldCharge/);
  assert.match(actions, /Process this batch first/);
  assert.match(processing, /hasMore/);
  assert.match(page, /activeConnectedAccountId: readStripeConnectedAccountId\(center\?\.customFields\)/);
  assert.match(processing, /if \(paymentMethod\.paymentMethodReauthorizationRequired\)/);
  assert.match(processing, /accountsWithActiveFamilyBalancePayments/);
  assert.match(processing, /activeDraftPayments/);
  assert.match(processing, /new Map\(\[\.\.\.payments, \.\.\.activeDraftPayments\]/);
  assert.match(processing, /await resolveStripeCheckoutDraftBlocker/);
  assert.doesNotMatch(processing, /now: asOf/);
  assert.match(processing, /createStripePaymentClaim/);
  assert.match(processing, /scope: "invoice_collection"/);
  assert.match(familyPayment, /createStripePaymentClaim/);
  assert.match(familyPayment, /scope: "family_balance"/);
  assert.match(paymentClaims, /FROM "BillingAccount"[\s\S]*FOR UPDATE/);
  assert.match(paymentClaims, /FROM "Invoice"[\s\S]*FOR UPDATE/);
  assert.match(paymentClaims, /provider: \{ in: \["stripe", "stripe_terminal"\] \}/);
  assert.match(paymentClaims, /invoice\.status !== PaymentStatus\.OPEN/);
  assert.match(paymentClaims, /invoice\.totalCents !== expectedInvoiceTotalCents/);
  assert.match(paymentClaims, /freshAllocation\.stripeChargePrincipalCents !== requestedAmountCents/);
  assert.match(paymentClaims, /existingPaymentId/);
  assert.match(paymentClaims, /reconcileIdempotentStripeSubmission/);
  assert.match(paymentClaims, /TransactionIsolationLevel\.Serializable/);
  assert.match(processing, /_submission_unknown/);
  assert.match(familyPayment, /checkout_submission_unknown/);
  assert.match(familyPayment, /director_saved_method_submission_unknown/);
  assert.match(terminalPayment, /createStripePaymentClaim/);
  assert.match(terminalPayment, /scope: invoice \? "invoice_collection" : "family_balance"/);
  assert.match(terminalPayment, /terminal_submission_unknown/);
  assert.match(terminalPayment, /terminal_reader_submission_unknown/);
  assert.match(terminalPayment, /terminal-payment:reader:\$\{payment\.id\}/);
  assert.match(terminalPayment, /accountCreditAppliedCents: invoiceCreditAllocation\?\.accountCreditAppliedCents \?\? 0/);
  assert.match(processing, /activeStripeAccountCreditReservationCents\(payment\)/);
  assert.match(paymentClaims, /activeStripeAccountCreditReservationCents\(payment\)/);
  assert.ok(
    familyPayment.indexOf("const activeFamilyCheckout") < familyPayment.lastIndexOf('if (method === "saved_method")'),
    "expired family Checkout drafts must be reconciled before saved-method claims",
  );
  assert.match(processing, /A family balance payment is already pending or processing; autopay is paused for this account\./);
  assert.match(processing, /prior payout account/);
  assert.match(workbench, /sendPaymentMethodRequest\("payment_method_reauthorization"\)/);
  assert.match(workbench, /Send replacement method link/);
  assert.match(workbench, /selectedPaymentMethod\?\.paymentMethodReauthorizationRecipientEmails/);
  assert.match(paymentRequests, /optionByEmail\.get\(email\)\?\.userIds\.includes\(enabledByUserId\)/);
  assert.match(paymentRequests, /linked guardian who enabled autopay/);
});
