import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("parent payment readiness audit checks balances, access, and account coverage without N+1 ledger reads", () => {
  const source = readFileSync("scripts/audit-parent-payment-readiness.ts", "utf8");

  assert.match(source, /livePaymentsEnabled === true/);
  assert.match(source, /tuitionBillingEnabled === true/);
  assert.match(source, /stripeSchoolBillingApproval/);
  assert.match(source, /currentlyEnrolledChildWhere/);
  assert.match(source, /parentVisibleBillingBalanceCents/);
  assert.match(source, /positiveBalancesWithoutActiveParentLink/);
  assert.match(source, /currentFamiliesWithoutBillingAccounts/);
  assert.match(source, /currentFamiliesWithoutActiveParentLink/);
  assert.match(source, /latestCreatedLedgerBalanceMismatches/);
  assert.match(source, /--include-exact-targets/);
  assert.match(source, /exactTargetFingerprint/);
  assert.match(source, /exactPositiveBalanceAccessTargets/);
  assert.match(source, /exactPositiveBalancesWithoutOpenInvoice/);
  assert.match(source, /hold_for_explicit_access_reactivation_approval/);
  assert.match(source, /hold_for_school_relationship_confirmation/);
  assert.match(source, /hold_for_contact_data_correction/);
  assert.match(source, /review_procare_source_package_and_child_provenance/);
  assert.match(source, /supported_account_balance_without_invoice/);
  assert.match(source, /manual_account_adjustment_needs_evidence_review/);
  assert.match(source, /missing_balance_ledger_history/);
  assert.match(source, /unsupported_positive_balance_provenance/);
  assert.match(source, /hasPositiveProcareOpeningBalance/);
  assert.match(source, /const lastSettledIndex = chronologicalLedger\.findLastIndex/);
  assert.match(source, /const balanceEvidenceWindow = chronologicalLedger\.slice/);
  assert.match(source, /unsupportedPositiveBalanceEvidence\.length > 0/);
  assert.match(source, /positiveBalancesWithoutOpenInvoiceNeedingEvidenceReview/);
  assert.match(source, /loadSupabaseAuthEmails/);
  assert.match(source, /activeAuthUser/);
  assert.match(source, /allAuthEmails/);
  assert.match(source, /activeAuthEmails/);
  assert.match(source, /auth_user_unconfirmed_or_banned/);
  assert.match(source, /hold_for_inactive_auth_identity_review/);
  assert.match(source, /const payerGuardians = family\.guardians\.filter\(\(guardian\) => guardian\.isBillingContact\)/);
  assert.match(source, /const payerAccessDiagnosis = diagnoseGuardianAccess\(payerGuardians\)/);
  assert.match(source, /isSupabaseAuthCompatibleEmail\(email\)/);
  assert.match(source, /paymentCenterTenantById/);
  assert.match(source, /parentPortalAccessDisabled\(guardian\.customFields\)/);
  assert.match(source, /guardian\.user\.email === normalizedEmail\(guardian\.user\.email\)/);
  assert.match(source, /data\.users\.length < 1000/);
  assert.match(source, /page \+= 1/);
  assert.doesNotMatch(source, /nextPage/);
  assert.doesNotMatch(source, /page <= 20/);
  assert.match(source, /activeParentLinksMissingAuth/);
  assert.match(source, /center\.balanceOnlyAccountsNeedingEvidenceReview > 0/);
  assert.match(source, /ledgerEntry\.findMany/);
  assert.match(source, /const ledgerEntriesByAccountId = new Map/);
  assert.match(source, /const accountLedger = ledgerEntriesByAccountId\.get\(account\.id\) \?\? \[\]/);
  assert.match(source, /const evidenceReviewReason = balanceEvidenceWindow\.length === 0/);
  assert.match(source, /!hasPositiveProcareOpeningBalance/);
  assert.match(source, /const needsEvidenceReview = evidenceReviewReason != null/);
  assert.match(source, /entry\.sourceSystem === "bee_suite_manual" && entry\.amountCents > 0/);
  assert.match(source, /payerAccessDiagnosis\.includes\("guardian_email_invalid"\)/);
  assert.match(source, /\.sort\(\(left, right\) => left\.id\.localeCompare\(right\.id\)\)/);
  assert.doesNotMatch(source, /accountIds\.map\([\s\S]{0,120}ledgerEntry\.findFirst/);
});

test("payer account preparation verifies complete app and Auth access and supports exact previews", () => {
  const source = readFileSync("scripts/prepare-payer-portal-accounts.ts", "utf8");

  assert.match(source, /--include-exact-targets/);
  assert.match(source, /activeAuthUser/);
  assert.match(source, /allAuthEmails/);
  assert.match(source, /Supabase Auth account is unconfirmed or banned/);
  assert.match(source, /parentPortalAccessDisabled\(guardian\.customFields\)/);
  assert.match(source, /guardian\.user\.tenantId === expectedTenantId/);
  assert.match(source, /activeAuthEmails\.has/);
  assert.match(source, /safeTargets/);
  assert.doesNotMatch(source, /page <= 20/);
});
